name: maven-push-to-ecr

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      AWS_REGION: us-west-2
      ECR_REPOSITORY: github-ecr-repo

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Maven Build
        run: mvn -B compile dependency:copy-dependencies -DincludeScope=runtime -s $GITHUB_WORKSPACE/settings.xml

      - name: Docker Build
        id: docker-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.ref_name }}
          # IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Docker Push
        id: docker-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.ref_name }}
          # IMAGE_TAG: ${{ github.sha }}
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
